services:
  app:
    container_name: agent_app
    build: .
    volumes:
      - ./laravel:/var/www
    command: ./start.sh
    ports:
      - "5173:5173"      # Vite (or npm run dev) port, if needed
      - "8000:8000"      # Artisan serve (Laravel)
    networks:
      - appnet
    depends_on:
      - db

  web:
    container_name: agent_web
    image: httpd:alpine
    ports:
      - "127.0.0.1:8123:80"          # Host 8123 maps to Apache 80 in container
    volumes:
     - ./laravel:/var/www
     - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
     - ./apache/proxy.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
     - ./empty:/usr/local/apache2/htdocs
    networks:
      - appnet
    depends_on:
      - app

  db:
    container_name: agent_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

networks:
  appnet:

volumes:
  dbdata:
