version: '3.8'
services:
  app:
    container_name: agent_app
    build: .
    volumes:
      - ./laravel:/var/www
    networks:
      - appnet
    depends_on:
      - db
  web:
    container_name: agent_web
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
    depends_on:
      - app
  db:
    container_name: agent_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet
networks:
  appnet:
volumes:
  dbdata:
